export const SearchUsers = [
  {
    avatar: 'https://i.pravatar.cc/150?img=11',
    isFollow: true,
    username: 'namcanh',
    firstname: 'Nam',
    lastname: 'Cảnh',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=12',
    isFollow: false,
    username: 'hoangthu',
    firstname: 'Hoàng',
    lastname: 'Thư',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=13',
    isFollow: false,
    username: 'minhchau',
    firstname: 'Minh',
    lastname: 'Châu',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=14',
    isFollow: true,
    username: 'anhkhoa',
    firstname: 'Anh',
    lastname: 'Khoa',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=15',
    isFollow: true,
    username: 'thanhtruc',
    firstname: 'Thanh',
    lastname: 'Trúc',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=16',
    isFollow: false,
    username: 'quanghuy',
    firstname: 'Quang',
    lastname: 'Huy',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=17',
    isFollow: false,
    username: 'ngocanh',
    firstname: 'Ngọc',
    lastname: 'Anh',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=18',
    isFollow: true,
    username: 'tuananh',
    firstname: 'Tuấn',
    lastname: 'Anh',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=19',
    isFollow: false,
    username: 'thuyduong',
    firstname: 'Thùy',
    lastname: 'Dương',
  },
  {
    avatar: 'https://i.pravatar.cc/150?img=20',
    isFollow: false,
    username: 'khanhlinh',
    firstname: 'Khánh',
    lastname: 'Linh',
  },
];
